# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mission_msgs/PayloadDropStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class PayloadDropStatus(genpy.Message):
  _md5sum = "ef1328b167874a2395c4858aac30705e"
  _type = "mission_msgs/PayloadDropStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool is_ready        # Drone ready status
int32 drone_id       # Identifier for the drone
time stamp          # Time when ready status was set
"""
  __slots__ = ['is_ready','drone_id','stamp']
  _slot_types = ['bool','int32','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       is_ready,drone_id,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PayloadDropStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.is_ready is None:
        self.is_ready = False
      if self.drone_id is None:
        self.drone_id = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.is_ready = False
      self.drone_id = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bi2I().pack(_x.is_ready, _x.drone_id, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.is_ready, _x.drone_id, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_Bi2I().unpack(str[start:end])
      self.is_ready = bool(self.is_ready)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bi2I().pack(_x.is_ready, _x.drone_id, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.is_ready, _x.drone_id, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_Bi2I().unpack(str[start:end])
      self.is_ready = bool(self.is_ready)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bi2I = None
def _get_struct_Bi2I():
    global _struct_Bi2I
    if _struct_Bi2I is None:
        _struct_Bi2I = struct.Struct("<Bi2I")
    return _struct_Bi2I
